# Generated by Django 5.2.8 on 2026-03-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoSentinelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
